// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW18gkF5ofjNC2W1JIIdwiCadQbGwjVLE',
    appId: '1:951274848218:web:a69430fe845f8f7b6b4ae3',
    messagingSenderId: '951274848218',
    projectId: 'fir-flutter-codelab-9929f',
    authDomain: 'fir-flutter-codelab-9929f.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-9929f.appspot.com',
    measurementId: 'G-F3H9WJJ9G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_NB2Fe_4Z82tLEXvZ7dYxLN2EC4x6T7c',
    appId: '1:951274848218:android:3b2fccb0933a71ae6b4ae3',
    messagingSenderId: '951274848218',
    projectId: 'fir-flutter-codelab-9929f',
    storageBucket: 'fir-flutter-codelab-9929f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-UPqoCz0l0UEc7BQo9zrXLQ0JsYJYZdw',
    appId: '1:951274848218:ios:19efbb422fddc5bc6b4ae3',
    messagingSenderId: '951274848218',
    projectId: 'fir-flutter-codelab-9929f',
    storageBucket: 'fir-flutter-codelab-9929f.appspot.com',
    iosClientId: '951274848218-036bqloem6r21e0kcjgcbgg6ccdrn7sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-UPqoCz0l0UEc7BQo9zrXLQ0JsYJYZdw',
    appId: '1:951274848218:ios:19efbb422fddc5bc6b4ae3',
    messagingSenderId: '951274848218',
    projectId: 'fir-flutter-codelab-9929f',
    storageBucket: 'fir-flutter-codelab-9929f.appspot.com',
    iosClientId: '951274848218-036bqloem6r21e0kcjgcbgg6ccdrn7sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
